### ISSUE TITLE
Develop an analytics page

### ISSUE THREAD

**Issue by WillianRod** [monizb/FireShort#113]
I'm opening this issue to start developing the Analytics page as mentioned in the README of this project.

The page is already under development, and I'm using this issue to ask some questions

Here are some ideas I have in mind:
- A visualization of the total of clicks of a link
- A visualization of the total of clicks today
- Avarage of clicks per day
- A graph showing clicks p/ day

Any other ideas?

Here are a quick view of what I've already done

![image](https://user-images.githubusercontent.com/6539258/95006802-996f0300-05de-11eb-8438-5c46190c1c24.png)

**Comment by monizb** [comment]
@WillianRod first of all thank you for our time and effort in contributing to this Repository, The page looks really clean! Here are some of my ideas:

1) Add a way to track the country of origin of each click and add to a total counter of each country and optionally show a map highlighting the countries based on how many clicks originated from them

2) Get referrer info of each click so that the user knows from where each click was generated in case they decide to share the link on various platforms

3) Since we are already tracking the User Agent, you could add the different platforms being used to click on the link

These are just ideas and you are free to implement them or not, thanks a lot once again :)

**Comment by WillianRod** [comment]
> @WillianRod first of all thank you for our time and effort in contributing to this Repository, The page looks really clean! Here are some of my ideas:
> 
> 1. Add a way to track the country of origin of each click and add to a total counter of each country and optionally show a map highlighting the countries based on how many clicks originated from them
> 2. Get referrer info of each click so that the user knows from where each click was generated in case they decide to share the link on various platforms
> 3. Since we are already tracking the User Agent, you could add the different platforms being used to click on the link
> 
> These are just ideas and you are free to implement them or not, thanks a lot once again :)

Cool, I'll work on it

**Comment by WillianRod** [comment]
To get info like country and other things you need to use some ip like [ipinfo.io](https://ipinfo.io)

`GET `https://ipinfo.io/YOUR_IP_HERE/json`

@monizb Do you mind making an API request on every click?

And what more information would you like to store?

This is what the api responds:
```json
{
   "ip": "string",
   "hostname": "string",
   "city": "string",
   "region": "string",
   "country": "string",
   "loc": "lat,lng",
   "org": "string",
   "postal": "string",
   "timezone": "America/Sao_Paulo",
   "readme": "string"
}
```

**Comment by monizb** [comment]
@WillianRod the API call shouldn't be a problem as long as it doesn't compromise with the actual wait time before redirecting to the destination link. Also I think we should be good with just the country name and the heat map, and we could extend it to include other data points later on if required.

**Comment by WillianRod** [comment]
@monizb  Any updates at https://github.com/monizb/FireShort/pull/120 ?
