### ISSUE TITLE
Pick any features from the checklist, fix an issue or add a feature of your choice - Hacktoberfest

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#5]
Feel free to start the discussion below and suggest what you would like to take up. The smallest of the contribution will be accepted and will count for one entry to your Hacktoberfest Progress

**Comment by alii13** [comment]
Hey, @monizb I want to add a loader during Sign-in to show the progress to the user & also found that the user needs to click on the Sign In button to make a login request.
I want to add accessibility to the Sign In button so that the user can make a login request by simply hitting Enter through the keyboard.
This is the first time I am making any contribution to someone repo :).

**Comment by monizb** [comment]
Hey @alii13 , that sounds pretty good to me, please go ahead with it :) Also welcome to the opensource world!

**Comment by alii13** [comment]
Hey, @monizb I created a pull request can you please review the code.

**Comment by JithinAntony4** [comment]
Hey @monizb I can take care of developing APIs for all the tasks with token-based authorization

**Comment by monizb** [comment]
@JithinAntony4 nyes please that would be helpful :). Please first raise a feature issue for the same thanks!

**Comment by vikashgaya916** [comment]
Links are not working unless the user of the link is logged in to the app. Is it a required? If not, I would like to work on this.
